export { default as Home } from './Home'
export { default as Conocenos } from './Conocenos'
export { default as Dashboard } from './Dashboard'
export { default as Preguntas } from './Preguntas'
export { default as Profile } from './Profile'
